kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  serviceName: "mysql-headless"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql

# pvc defination directly mentioned in statefulset
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: mysql-ebs
        resources:
          requests:
            storage: 1Gi

# normal service - clusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306

# headless service
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306